# Generated by Django 4.2.4 on 2023-09-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
